[rule]
description = """
This rule detects non-dd processes with command lines that reference a process memory file under procfs. Access to
"/proc/<pid>/mem" or its thread-specific equivalent can be used to read sensitive process memory or modify a running
process.
"""
id = "4f548b1e-64ac-472f-a42d-e9f44ba9afa8"
license = "Elastic License v2"
name = "Potential Process Memory Access via Procfs"
os_list = ["linux"]
reference = [
    "https://man7.org/linux/man-pages/man5/proc_pid_mem.5.html",
    "https://attack.mitre.org/techniques/T1003/007/",
]
version = "1.0.3"

query = '''
process where event.type == "start" and event.action == "exec" and (
  process.name in (
    "cat", "less", "more", "head", "tail", "nano", "vi", "vim", "strings", "nvim", "vim.basic",
    "vim.tiny", "od", "hexdump", "xxd", "hx", "hexedit", "pager", "tr"
  ) or
  (
    process.name in (
      "find", "awk", "gawk", "mawk", "nawk", "grep", "fgrep", "rgrep", "xargs", "sed", "tee"
    ) and
    process.args_count <= 20
  )
) and process.command_line like ("*/proc/*/mem *", "*/proc/*/task/*/mem *", "*/proc/*/mem", "*/proc/*/task/*/mem") and
not process.args like ("*/proc/pressure/memory", "/proc/pressure/memory/comm", "/proc/*/mem/comm")
'''

min_endpoint_version = "8.3.0"
optional_actions = []
[[actions]]
action = "kill_process"
field = "process.entity_id"
state = 0

[[threat]]
framework = "MITRE ATT&CK"
[[threat.technique]]
id = "T1003"
name = "OS Credential Dumping"
reference = "https://attack.mitre.org/techniques/T1003/"
[[threat.technique.subtechnique]]
id = "T1003.007"
name = "Proc Filesystem"
reference = "https://attack.mitre.org/techniques/T1003/007/"



[threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[internal]
min_endpoint_version = "8.3.0"
